### ISSUE TITLE
ClickHouseRowBinaryStream doesn't support arrays

### ISSUE THREAD

**Issue by genuss** [yandex/clickhouse-jdbc#107]
There is a lack of implementation. I tried to implement it by myself but got no luck. Here is a sample method for string array:
````java
public void writeArray(String[] array) throws IOException {
        Preconditions.checkNotNull(array);
        writeUnsignedLeb128(array.length);
        for (String el : array) {
            writeString(el);
        }
}
````
With this implementation I get ``DB::Exception: Cannot read all data`` from clickhouse server version 1.1.54236.
Do you see what can be wrong with this code?

**Comment by serebrserg** [comment]
@AndreevDm , do you see what needs to be done to support arrays in RowBinary?

**Comment by AndreevDm** [comment]
@genuss you implementation is correct. Where is a small bug in writeString() function, i'll try to fix it today.

**Comment by genuss** [comment]
Hah, today rechecked and it looks like my fault and this implementation actually works. Would you like me to submit a PR for all arrays string or numbers?
