### ISSUE TITLE
Error when using Spark - Syntax error: failed at position 8

### ISSUE THREAD

**Issue by sigurdurm** [yandex/clickhouse-jdbc#117]
Spark: 2.1.0 (Hadoop 2.7)
Java/Python

When querying using spark and clickhouse jdbc driver (newest source, head 164d10c), we got this error:
```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: 
Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, 192.168.1.179, executor 2): 
ru.yandex.clickhouse.except.ClickHouseException: 
ClickHouse exception, code: 62, host: clickhouse, port: 8123; 
Code: 62, e.displayText() = DB::Exception: 
Syntax error: failed at position 8: "name","city","country" FROM default.spark FORMAT TabSeparatedWithNamesAndTypes;, 
expected not empty list of expressions, e.what() = DB::Exception
```

Caused by this line in the code:
https://goo.gl/73N8Ya

Our java spark code looks like this:
```
HashMap<String, String> clickhouseOptions = new HashMap<String, String>() {{
    put("driver", "ru.yandex.clickhouse.ClickHouseDriver");
    put("url", "jdbc:clickhouse://clickhouse:8123");
    put("dbtable", "default.spark");
}};

SparkSession spark = SparkSession.builder().getOrCreate();
Dataset<Row> test = spark.read().format("jdbc").options(clickhouseOptions).load();
test.show();
```

When calling ```show()``` the error happens.

The *default.spark* table has three columns *name, city, country*
The select query looks like this, coming form Spark:
```SELECT "name","city","country" FROM default.spark```

After clickhousifySql(sql), https://goo.gl/1wAuWb:
```SELECT "name","city","country" FROM default.spark FORMAT TabSeparatedWithNamesAndTypes;```

The problem lies in the **quotation marks**, removing them or replacing with a back quote, to support spaces in column names, solves the error:
```SELECT `name`,`city`,`country` FROM default.spark FORMAT TabSeparatedWithNamesAndTypes;```

**Comment by serebrserg** [comment]
This must work with server >= 1.1.54245.
Quote from the linked pull request:
> BTW, we have added support of SQL double quotes in today version of ClickHouse (1.1.54245).

**Comment by drauschenbach** [comment]
I'm still experiencing this with:
* Server 20.1.4.14 with revision 54431 via Docker (Feb 10 2020)
* JDBC Driver 0.2.4 (Feb 2020)
