### ISSUE TITLE
ClickHouseStatementImpl.getUpdateCount() doesn't signal no more results

### ISSUE THREAD

**Issue by peturrun** [yandex/clickhouse-jdbc#132]
The implementation of ClickHouseStatementImpl.getUpdateCount() will always return 0 if the previous statement didn't return a result set, no matter how often getMoreResults() is called. This causes a loop that tries to read all results from a Statement to loop forever since the following expression from the JavaDoc for Statement is always false:

`((stmt.getMoreResults() == false) && (stmt.getUpdateCount() == -1))`

**Comment by serebrserg** [comment]
Thanks.
Merged your PR. Released in 0.1.28.

**Comment by peturrun** [comment]
Thank you!

**Comment by peturrun** [comment]
By the way, this was discovered when trying to use Flyway (http://flywaydb.org) for schema migration on ClickHouse. This is now working, and is available from here: https://github.com/activitystream/flyway
