### ISSUE TITLE
Return types incorrect for nullable values

### ISSUE THREAD

**Issue by HelgiHelgason** [yandex/clickhouse-jdbc#140]
When we select a value that is nullable (i.e. Nullable(Float)), what we get back from the JDBC driver is a value of type String. Looking at the code it seems that only non-nullable Float, Int and UInt are currently supported return types, with everything else being converted to String. Would be great to get a fix for this, so that upon selecting a Nullable(Float) value we actually get back a value of type Float.

**Comment by serebrserg** [comment]
Thanks for report.
Merged to master. Will be in next release. 
So for proper Nullable(<Type>) rs.getMetaData().getColumnType(1) will return value associated with <Type> and for getObject object of correct class will be returned.

**Comment by serebrserg** [comment]
released in 0.1.29
