### ISSUE TITLE
Magic is not correct 105 instead of correct error

### ISSUE THREAD

**Issue by serebrserg** [yandex/clickhouse-jdbc#146]
Usually happens when user is not allowed to connect from the host.

**Comment by TanVD** [comment]
Is it possible to parse those kinds of errors into human readable form? It could be really helpful.

**Comment by serebrserg** [comment]
As I know the problem is that we expect sever response to be compressed when in some cases it is not.
Currently as a workaround you can disable compression in the driver to have readable error message. When you have fixed the settings to have no exception, you can turn compression back on.

**Comment by TanVD** [comment]
I understand. But as far as I see, it is clear from response of server, that result is not compressed and almost always in that case repsponse is error message. Is it possible, to print response to log.error, in case if compressed response expected, but got not compressed?

**Comment by vsmelov** [comment]
@serebrserg 
but how can I disable compression on driver?
Is there some option or something like this?

**Comment by serebrserg** [comment]
You can also set it through Properties or ClickHouseProperties.

Regarding 

> Is it possible, to print response to log.error, in case if compressed response expected, but got not compressed?

I think the error must be parsed correctly as ClickHouseException with correct code. This may be done by trying to parse value as not compressed if parsing as compressed had failed.

**Comment by serebrserg** [comment]
Released in 0.1.31
