### ISSUE TITLE
Cannot Get Table Object via JDBC

### ISSUE THREAD

**Issue by shahvishal8464** [yandex/clickhouse-jdbc#147]
I am trying to use Table[] tables = ((JdbcDataContext) jdbc).getSchemaByName("default").getTables(); to get a list of tables belonging to default schema. However this method returns a null value. 

Also the method Table table = jdbc.getDefaultSchema().getTableByName("temp"); doesn't seem to work. Is there a way by which I can get the Instance of the specified table or all the tables belonging to that schema?

**Comment by serebrserg** [comment]
There are three TableTypes currently defined in clickhouse-jdbc: TABLE (for real tables), VIEW(for views, Merge and Distributed), OTHER(for Memory, Set, Join and Buffer). The types are returned from connection.getMetaData().getTableTypes() .
You should create JdbcDataContext passing all table types returned from metadata to be able to see all tables. JdbcDataContext(Connection c) instantiates context including only TABLE and VIEW types. You probably can not find tables from OTHER category.
If written above is not correct, please devise more localized case description: what is expected from jdbc-driver in which method calls and what it returns, preferably in form of unit test.

**Comment by shahvishal8464** [comment]
Thank you for your suggestion @serebrserg It totally helped me out. The problem was with the DB Engine that I was using. Apparently I had to use MergeTree Engine instead which solved my problem in an instant. Once again Thank you for your invaluable input.
