### ISSUE TITLE
Translate Statement#setMaxRows() into LIMIT clause

### ISSUE THREAD

**Issue by tobia** [yandex/clickhouse-jdbc#16]
Using graphical JDBC clients to browse ClickHouse tables, I noticed that the row limit / pagination features of the clients (and thus their table browsing interfaces) practically do not work. What I mean is that on sufficiently large tables, the queries take so much time that they are useless in practice (and eventually fail anyway.)

The reason is that the graphical clients use Statement#setMaxRows() to set the number of rows they are interested in before executing the query, as per JDBC specs. But the driver does not send that information to the server, sending instead a limitless query via HTTP POST.

By its nature, being throughput-oriented, ClickHouse will interpret a limitless query as really wanting the entire table, and so will take a long time to prepare the result set, which in many cases will not fit in the server memory and thus will eventually fail.

I believe ClickHouseStatementImpl should add maxRows to the query source as a LIMIT clause (before adding FORMAT) if that option was set by the JDBC client, instead of sending a limitless query and then truncating the result set.

**Comment by serebrserg** [comment]
Thanks for notion.
Adding LIMIT clause before FORMAT won't work in some cases, for example when there is a UNION ALL. To handle this (and other potential cases I don't know about yet) by modifying query is quite invasive and gives a lot of space to mess this all up.
As I know the common approach is to send this kind of limit by a separate query parameter. I'll check if it is possible.

**Comment by alexey-milovidov** [comment]
Look at `max_result_rows` and set `result_overflow_mode = 'break'`.
It is not the same as LIMIT, because slightly more rows may be returned.

**Comment by serebrserg** [comment]
Merged to master. Will be in the next release version.
