### ISSUE TITLE
Problem with ClickHouseDatabaseMetadata

### ISSUE THREAD

**Issue by yuragr76** [yandex/clickhouse-jdbc#160]
In method getColumns code
`// decimal digits`
`if (sqlType == Types.INTEGER || sqlType == Types.BIGINT && type.contains("Int")) {`
`                String bits = type.substring(type.indexOf("Int") + "Int".length());`
`                row.add(bits);`
`            } else {`
`                row.add(null);`
`            }`

must return '16)' if column has type Nullable(UInt16)

**Comment by serebrserg** [comment]
Must have been fixed in related PR.
