### ISSUE TITLE
Implement WITH TOTALS support

### ISSUE THREAD

**Issue by IgnatBeresnev** [yandex/clickhouse-jdbc#161]
What I'm suggesting is we add a getter `getWithTotals()` to `ClickHouseResultSet` for those that really need it. This way, `WITH TOTALS` is supported and at the same time is not among the actual ResultSet results, so no unexpected information or behaviour there.

Supposedly, it'll be populated during one of `next()` calls (if you have any better ideas - let me know) and the user will be able to extract it after iterating over ResultSet.

I'll be happy to have a go at this and, if successful, send a PR.

**Comment by serebrserg** [comment]
Hi, this would be nice.
You can also add getExtremes() with same functionality which returns min and max. By the way this can be configured through properties but is turned off by default because it is quite tricky to implement.

Yes, you can fill the values during iteration on main ResultSet. Totals and Extremes are in the end of the stream, so I think it must be stated that they are available only after the main ResultSet is exhausted.
Then one can call getTotals() or getExtremes() and either receive either new ResultSet with totals or extremes, or use the same ResultSet with some internal pointers reset.
So first option would look like
```java
ResultSet totalsRs = rs.getTotals();
if(totalsRs.next()) {
  // receive totals values
}
```
or second:
```java
rs.totals();
if(rs.next()) {
  // receive totals values
}
```
I have no strict preference between these two. 
Let me know if you have different ideas.

**Comment by IgnatBeresnev** [comment]
I think first is better since it's more intuitive and scalable. I'll start working on it tonight.

**Comment by hamsterready** [comment]
Hi guys, any progress on this one? Let me know if there is any active branch with this.

**Comment by IgnatBeresnev** [comment]
@hamsterready still haven't had a chance to even look at it, a lot went down IRL. Hopefully these weekends I'll be able to have a go at this issue 

If you want to start doing it earlier, feel free to, just let us know :)

**Comment by IgnatBeresnev** [comment]
@serebrserg it indeed is tricky to implement. 

The biggest problem arises when it's only 1 column in the result.  For insatnce, if we select 1 column where the result looks like 

column | 
------------ | 
Something | 
Something | 
(empty) | 
Something | 

it'll be sent as `Something\nSomethin\n\nSomething`, which is exactly the same as if we do `SELECT ... WITH TOTALS` on 1 column.

I don't know who would do a `GROUP BY ... WITH TOTALS` on one column, but it might happen. If execute such a query now, it'll work just fine and won't throw an exception (but > 1 column queries with `WITH TOTALS` fail on columns.length check), and `WITH TOTALS` result will be among the actual result in the resultSet (in the end, after an empty element that really shoudn't be there)

So, as far as I understand, right now there's no way to distinguish `WITH TOTALS` result on 1 column vs a couple of empty rows (both can be in the end) in select on 1 column. The only way to understand it's NOT `WITH TOTALS` is if the number of columns (tabs) is greater than what we have after the last `\n\n`. 
__________________________

So the way to implement `WITH TOTALS` support would be to check the row right after the last `\n\n`, and if the number of tabs < `columns.length`, then we consider it to be the `WITH TOTALS` result. We exclude it from the result processing and save it somewhere to be called later.  If number of tabs after `\n\n` == 1 OR == `columns.length`, then we do nothing and process it as usual. 

Moreover, this works only if the flag `with_totals_support` (or whatever, it's not the point) is set to true in `ClickHouseProperties`

Pros:
* Doesn't break current results processing

Cons:
* No support for `WITH TOTALS` on 1 column 
* Doesn't solve `WITH TOTALS` being incorrectly processed on 1 column results (it adds an exsessive empty row and is among main results)

__________________________
P.S, It's been a few days since I debugged this, so I might be wrong in some specific implementation details, but overall the idea is still the same. Let me know if you need actual details with examples

**Comment by serebrserg** [comment]
I think you can find out if totals must be returned by looking at ClickhouseProperties and searching WITH TOTALS in request. There may be peculiarities regarding the place in query where it is written, so it may be not exact way to distinguish in some cases. It should cover most popular cases and they should be described. I think it is better than not to work in single column case at all.
If you decide that totals must be returned, then there are two cases:
- several columns: you can read till empty line as you described and expect totals line after it
- one column: you can read till the end, expect last line to be totals and previous line to be empty

**Comment by IgnatBeresnev** [comment]
I see this issue has now been resolved, awesome :) 

Sorry that I wasn't able to provide an implementation myself, it's been a rough time.
