### ISSUE TITLE
ClickHouseResultSetMetaData nullable check always returns false

### ISSUE THREAD

**Issue by svetlana-kulygina** [yandex/clickhouse-jdbc#164]
I am trying to use clickhouse with Spark SQL.
Here is nullable field check from `JdbcUtils.getSchema` :

`val nullable = rsmd.isNullable(i + 1) != ResultSetMetaData.columnNoNulls`

But `ClickHouseResultSetMetaData.isNullable` implementation does not really respect column type:
```
    @Override
    public int isNullable(int column) throws SQLException {
        return columnNoNulls;
    }
```
Seems it should be like:
```
String clickhouseType = resultSet.getTypes()[column - 1]
return clickhouseType.startsWith("Nullable(") && clickhouseType.endsWith(")") ? columnNullable : columnNoNulls;
```

**Comment by serebrserg** [comment]
Must be fixed in #266
