### ISSUE TITLE
Problem when use 'WITH TOTAL' expression

### ISSUE THREAD

**Issue by hacker13ua** [yandex/clickhouse-jdbc#169]
When i try to execute query using 'WITH TOTAL', i get 

> ClickHouseUnknownException: ClickHouse exception, code: 1002, host: unknown, port: -1;

Problem in validation method
```
private void checkValues(String[] columns, ByteFragment[] values, ByteFragment fragment) throws SQLException {
        if (columns.length != values.length) {
            throw ClickHouseExceptionSpecifier.specify(fragment.asString());
        }
    }
```

**Comment by serebrserg** [comment]
Hello,
The problem must have been fixed in 0.1.35.
If the problem can still be reproduced in the last version, please reopen and describe a test case to reproduce the issue.
