### ISSUE TITLE
Some errors are displayed wrong

### ISSUE THREAD

**Issue by serebrserg** [yandex/clickhouse-jdbc#178]
```
ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 173, host: 192.168.33.10, port: 8123; Cq O/��򗴍�ܠ [��   �   �QCode: 173, e.displayText() = DB::Exception: Allocator: Cannot mmap 64.00 MiB., errno: 12, strerr-  a? �e memoryq ;whaj Ption
```

**Comment by tkroman** [comment]
I think this is due to the fact that the whole entity body is printed to string and for byte arrays and compressed data that's not the best option. Maybe trying to decode the entity to readable form and printing it later would make more sense.
