### ISSUE TITLE
Setting password

### ISSUE THREAD

**Issue by rasmus93** [yandex/clickhouse-jdbc#2]
I cannot find possibility to set password with jdbc-driver.
And as I see password is not used when you create connection:
`public Connection getConnection(String username, String password) throws SQLException {
    return driver.connect(url, properties);
}`
@serebrserg, maybe, there is something that I had not noticed? Can you help me with this?

**Comment by serebrserg** [comment]
You are right, there is no possibility to set password now. This will be added soon.

**Comment by rasmus93** [comment]
Thanks!

**Comment by serebrserg** [comment]
available in 0.1.2
