### ISSUE TITLE
ClickHouseArrayUtil - NullPointerException

### ISSUE THREAD

**Issue by RazieI** [yandex/clickhouse-jdbc#211]
Добрый день.

Версия драйвера release_0.1.39.

При сериализации массива не учитывается возможность присутствия в нем значений NULL.
Для всех значений входного массива в методе `append(Object value)` вызывается следующий код:
`String serializedValue = value.toString();`

Это является причиной исключения.

**Comment by milktea02** [comment]
I think this fixes the problem but has not yet been released:
https://github.com/yandex/clickhouse-jdbc/pull/199

**Comment by serebrserg** [comment]
Released in 0.1.40
