### ISSUE TITLE
How I can get WITH TOTALS result?

### ISSUE THREAD

**Issue by arturgspb** [yandex/clickhouse-jdbc#22]
Hi!

Example query:

"
SELECT EventDate, count() AS c 
FROM test.hits 
GROUP BY EventDate 
WITH TOTALS 
ORDER BY EventDate
"

Where in ResultSet I can get totals?

**Comment by arturgspb** [comment]
Hey! @serebrserg

**Comment by alexey-milovidov** [comment]
Hello. Serebrserg is on vacation till 25 September.

**Comment by serebrserg** [comment]
Hello, I can not browse the code conveniently now. As I remember the only
way to achieve totals now is to query with executeQueryClickhouseResponse
method of ClickHouseStatement. In The case ClickHouse will be queried with
json result format.The dowbside os that the whole result must fit in memory
and it consists of Strings.

16 сент. 2016 г. 3:28 PM пользователь "alexey-milovidov" <
notifications@github.com> написал:

**Comment by arturgspb** [comment]
@alexey-milovidov @serebrserg thx a lot!

**Comment by serebrserg** [comment]
Yes, I have checked in the code, this is the only way to achieve totals now.

**Comment by hamsterready** [comment]
Just for the record, there is #161 which covers implementation of the `with totals` support.
