### ISSUE TITLE
Does it support scrollable Resultset ?

### ISSUE THREAD

**Issue by gong** [yandex/clickhouse-jdbc#220]
like mysql 
Statement s = dbConnection.createStatement(
  ResultSet.TYPE_FORWARD_ONLY,
  ResultSet.CONCUR_READ_ONLY);
s.setFetchSize(Integer.MIN_VALUE);

**Comment by serebrserg** [comment]
Scrollable ResultSets are not implemented.
Implementing TYPE_SCROLL_INSENSITIVE for example would need to store the whole ResultSet in client's memory, which as a workaround may be done outside the driver in client code explicitly.
TYPE_SCROLL_SENSITIVE is not that straightforward. I can't think of reasonable way of providing this functionality now - this would anyway require to recalculate the query.
