### ISSUE TITLE
The question about the count function

### ISSUE THREAD

**Issue by updateByMe** [yandex/clickhouse-jdbc#243]
Using the count query, when there is no data, a 0 will be given, and when it will show '0 rows in set. Elapsed: 0.002 SEC.' comment

**Comment by serebrserg** [comment]
Hello.
Could you describe the problem in more detail? What do you do exactly and what do you expect? Which interface are you using: clickhouse-client or clickhouse-jdbc? I think you can't get "0 rows in set" using clickhouse-jdbc.
