### ISSUE TITLE
Parsing RowBinary result set?

### ISSUE THREAD

**Issue by bgranvea** [yandex/clickhouse-jdbc#271]
I would like to have the possibility to execute a query and get a result in RowBinary format. This would allow a more efficient parsing of the result when the result contains lots of rows.

I know it can be done in HTTP but IMHO it is interesting to add it to the JDBC driver as it allows to stay in a consistent API and migrate only some statements.

What do you think? I'm ready to start working on it.

BTW, is there a plan to implement at some point the native format (for insert and/or select)?

**Comment by serebrserg** [comment]
I would prefer not to expose an additional interface in RowBinary form. I wonder if it is possible to separate result parsing to the smallest possible interface to make it possible to change implementation from TSV to RowBinary or native, or maybe implement a different version of ResultSet basing on RowBinary format, and change implementation though settings.

Regarding plans on implementing native format, I have some kind of basic trial implementation for selects, but I am not sure I will get to making it mature enough to be used reasonably soon. Maybe I will publish it to a branch, but some cleaning and adopting still needs to be done.

**Comment by bgranvea** [comment]
I understand your concern about the API but I don't see how to use a common ResultSet class for TSV and RowBinary. The main reason is that RowBinary doesn't contain metadata such as column names and types, so we must rely on the caller to extract the data with the right function (readString, readUInt32...). With respect to this, the native format is a better alternative as it contains more information.

Maybe we should distinguish between formats with metadata that can be parsed by the JDBC driver and the others?

If you really want to have a common ResultSet class, you can create a RowBinaryResultSet subclass with no implementation for getString(position/name), getInt() and specific functions getUInt64(), getString(). 

A variant is to have ResultSet give an access to a result stream. It would return a RowBinaryStream which contains readUInt32... For TSV, it would just return strings in stream order.

**Comment by serebrserg** [comment]
I didn't realize at first that RowBinary doesn't have metadata. In this case I think it is ok to expose RowBinaryInputStream. We already have result as parsed object from json anyway.

**Comment by bgranvea** [comment]
so just to be sure, you mean adding a method to ClickHouseStatement like this?

`ClickHouseRowBinaryInputStream executeQueryClickhouseRowBinaryStream(String sql)
`

**Comment by serebrserg** [comment]
yes
