### ISSUE TITLE
Driver is not available in maven central

### ISSUE THREAD

**Issue by pshirshov** [yandex/clickhouse-jdbc#30]
Hi guys,

It's definitely a good idea to make driver available with Maven Central.

Конторе привет от @viasyn :з

**Comment by serebrserg** [comment]
Hi.
Here it is:
http://search.maven.org/#artifactdetails%7Cru.yandex.clickhouse%7Cclickhouse-jdbc%7C0.1.9%7Cjar
And there is a maven badge at project description page (README.md).

If I didn't understand you correctly, please tell me.

**Comment by pshirshov** [comment]
Hi,

Hm, yep, I see it there right now. Maybe it was just some kind of problem with central search engine.
