### ISSUE TITLE
Fix ClickHouseResultSetMetaData#getColumnClassName for Arrays

### ISSUE THREAD

**Issue by enqueue** [yandex/clickhouse-jdbc#300]
The current implementation of `ClickHouseResultSetMetaData#getColumnClassName` returns a wrong class name for Array data types.

Example:

```
Statement stmt = connection.createStatement();
ResultSet rs = stmt.executeQuery("SELECT array(42, 23)");
rs.next();
System.out.println(rs.getMetaData().getColumnClassName(1));
```

Output is: `[Ljava.lang.Long;`

This is not a good class name :wink: Instead we should return `java.sql.Array`

**Update 2019-03-03**

As @serebrserg  points out, the driver should be consistent, i.e. the class of the object returned by `ResultSet.getObject` should correspond with the class name returned by `ResultSetMetaData.getColumnClassName`. There is now a test for this (PR #320)

Looking at the [JDBC specification](https://jcp.org/en/jsr/detail?id=221), there is a recommended mapping, we might want to implement (see tables B-1, B-3 in the appendix)

Table B-1 (JDBC Types Mapped to Java Types)

> This table shows the conceptual correspondence between JDBC types and Java types. A programmer should write code with this mapping in mind. For example, if a value in the database is a SMALLINT, a short should be the data type used in a JDBC application.

| JDBC Type |Java Type |
|-------------|-----------|
| ... | ... |
| ARRAY | `java.sql.Array`|

Table B-3 (JDBC Types Mapped to Java Object Types)

> ResultSet.getObject and CallableStatement.getObject use the mapping shown in this table for standard mappings.

| JDBC Type | Java Object Type |
|-------------|--------------------|
| ... | .. |
| ARRAY | `java.sql.Array` |

**What do others do?**

| JDBC Driver | Behaviour |
|--------------|-------------|
| [pgjdbc](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java) | `java.sql.Array` |
| [mysql-connector-j](https://github.com/mysql/mysql-connector-j) | MySQL does not support Array, as far as I know ([WL 2081](https://dev.mysql.com/worklog/task/?id=2081)) |
| Oracle | <p>See [documentation](https://docs.oracle.com/en/database/oracle/oracle-database/18/jjdbc/Oracle-collections.html#GUID-BC05FE69-643F-44AF-8D86-2E181F7E6628)</p><ul><li>Create  new array type, like so: <code>CREATE OR REPLACE TYPE myarray IS VARRAY(2) OF VARCHAR2(3);</code></li><li>Query: <code>ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM MYTABLE");</code></li><li><code>rs.getMetaData()</code> returns <code>oracle.jdbc.OracleArray</code> for column class name (this is the Oracle specific sub-interface for <code>java.sql.Array</code>), <code>Types.ARRAY</code> for column type. The actual object's class is <code>oracle.sql.ARRAY</code> which in turn implements <code>oracle.jdbc.OracleArray</code></li></ul> |
| Microsoft | `java.lang.Object` ? [DataTypes](https://github.com/Microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/DataTypes.java) |
| IBM DB2 | <p>It is complicated. I _think_ that arrays may not be used for real columns. It is not mentioned in the mapping table for column types, and the footnote for parameters says, that an Array may only be used for Stored Procedures. While `getArray` is supported, I have not been able to compare the behavior of `getColumnClassName` with `getObject`</p><ul><li>[Data types that map to database data types in Java applications](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_rjvjdata.html)</li><li>[DB2 SQL Reference](http://publib.boulder.ibm.com/epubs/pdf/dsnsqn02.pdf)</li><li>`getColumnClassName` is also "not supported" by the DB2 JDBC driver, see table 22 in [Driver support for JDBC APIs](https://www.ibm.com/support/knowledgecenter/en/SSEPEK_12.0.0/java/src/tpc/imjcc_rjvjdapi.html)</li></ul> |
| [H2](http://www.h2database.com/html/cheatSheet.html) | Interesting: `getColumnClassName` returns `java.sql.Array` but the returned Object is actually a `String[]`| 
| [FirebirdSQL jaybird](https://github.com/FirebirdSQL/jaybird) | `java.sql.Array`, see [AbstractFieldMetaData](https://github.com/FirebirdSQL/jaybird/blob/master/src/main/org/firebirdsql/jdbc/AbstractFieldMetaData.java) and [JavaTypeNameConstants](https://github.com/FirebirdSQL/jaybird/blob/master/src/main/org/firebirdsql/jdbc/JavaTypeNameConstants.java) |

Especially considering the recommendations from the specification, but also taking into account the other drivers, I think that the ClickHouse driver should return `java.sql.Array` or a specialized interface. The `getObject` method would then have to be adjusted. This might break some clients :warning: , but I would consider it more standard-compliant.

**Comment by serebrserg** [comment]
Thanks for PR.
Do you have a refference why this must be that way? I didn't find exact description in the docs.
As I understand this must be alligned with type of ResultSet.getObject() return value, and this is not java.sql.Array, but actual array.

**Comment by enqueue** [comment]
You are absolutely right, this is inconsistent. Let me research this a little bit.

**Comment by serebrserg** [comment]
Sorry for long wait. 
I agree with the solution.

**Comment by enqueue** [comment]
Thanks for the review!
