### ISSUE TITLE
SimpleDateFormat is not thread safe

### ISSUE THREAD

**Issue by rasmus93** [yandex/clickhouse-jdbc#31]
In class ClickHouseResultSet there is static SimpleDateFormat which is not thread safe.
Could you replace it with something else or use syncronizing or thradLocal for this?

**Comment by serebrserg** [comment]
Hello,
Thanks. This is clearly a bug.
In fact it is ok if the SimpleDateFormat fields are not static because single ResultSet does not guarantee any thread safety.

**Comment by serebrserg** [comment]
done in 0.1.11

**Comment by rasmus93** [comment]
Yeah, it is good solution. Thanks!
