### ISSUE TITLE
bad description (copy & paste error) 

### ISSUE THREAD

**Issue by filimonov** [yandex/clickhouse-jdbc#310]
See https://github.com/yandex/clickhouse-jdbc/blob/4bc44ba1ba1ebbfe5293c08c48cf8d607ed8da60/src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java#L227

**Comment by enqueue** [comment]
Do you think that the parameter can be removed altogether? It looks more like a server setting than a per-query parameter.

**Comment by filimonov** [comment]
> Do you think that the parameter can be removed altogether? It looks more like a server setting than a per-query parameter.

`uncompressed_cache_size` is a server-wide setting, but `use_uncompressed_cache` as it is a valid per-query setting, so you can turn it on/off for particular queries.

**Comment by enqueue** [comment]
Thanks for the clarification!
