### ISSUE TITLE
Cannot override setting (result_overflow_mode) in readonly mode

### ISSUE THREAD

**Issue by enqueue** [yandex/clickhouse-jdbc#324]
I am trying to run a query using a read-only user, but the server complains about `result_overflow_mode` setting not being available for read-only connections.

**Comment by blinkov** [comment]
@enqueue configure your user with `readonly=2` setting.

**Comment by enqueue** [comment]
@blinkov  thanks! I should RTFM first, thought this was a binary switch ;-)
