### ISSUE TITLE
ERROR: text "<SINGLE QUOTE>2016-08-1" is not like DateTime

### ISSUE THREAD

**Issue by simPod** [yandex/clickhouse-jdbc#333]
This is the error I see in clickhouse when trying to batch insert

```
2019.04.17 00:08:45.729957 [ 264 ] {0e04b028-f581-4c85-a668-1b3c1d744863} <Error> HTTPHandler: Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected \t before: \'2016-08-12 13:21:32\'\t32767\t\'163.172.36.163\'\t\'185.229.191.169\'\t1522\t1\t0\t0\t0\t1000003\t1000010\t8080\t12724\t16\t\'128110002367193\'\t\'116530121835\'\t968\t968\t968\t\'\'\t\'Amste: (at row 1)

Row 1:
Column 0,   name: received_at,     type: DateTime, ERROR: text "<SINGLE QUOTE>2016-08-1" is not like DateTime
```

I'm using the same code as is in test here https://github.com/yandex/clickhouse-jdbc/blob/d75f1594b9eebcab200b27bc426b136233b1b927/src/test/java/ru/yandex/clickhouse/integration/BatchInsertsTest.java#L99 Even the same value.

[Thus I blame the newer ClickHouse version I'm running (19.4.3.11)](https://github.com/yandex/clickhouse-jdbc/issues/332).

**Comment by simPod** [comment]
Also this doesn't work:

`statement.setString(1, format.format(new Date(long * 1000L)));` same error

I changed the DateTime to UInt32 and all inserts pass through without problem `statement.setLong(1, long);`

**Comment by simPod** [comment]
I just noticed it inserts string values with quotes. Like `'163.172.83.181'` instead of `163.172.83.181`. That will be the problem.

**Comment by simPod** [comment]
And this works:

```java
SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
statement.setBytes(1, format.format(new Date(long * 1000L)).getBytes());
```

So the problem is in escaping I guess https://github.com/yandex/clickhouse-jdbc/blame/149967fd91d3d1191254188603951df09c6061bb/src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java#L208 Can't help further tho, don't really undestand what happens there.

**Comment by Baoqi** [comment]
I also encountered this issue today, as it turns out, when you use prepared statement to batch insert values, if you see

```
Like '163.172.83.181' instead of 163.172.83.181
```

it means in PreparedStatementParser.java,  your sql is not classified as "valuesMode".

https://github.com/yandex/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/PreparedStatementParser.java#L19

```
    private static final Pattern VALUES = Pattern.compile(
"(?i)INSERT\\s+INTO\\s+.+VALUES\\s*\\(");
```
Then, it turns out my SQL is multiple line. like:

```
insert into table1
  (col1, col2)
values
  (?, ?)
```

this will not match the regex. So, my work around is, before send sql to clickhouse's prepare, I replace all \r  \n  with empty space. Then, the datetime can be inserted into database successfully.

Is this also your case?

**Comment by simPod** [comment]
Yes, definitelly. I import huge sql file with INSERT statement that is pretty-formatted. When I one-line it it passes.

**Comment by poslegm** [comment]
Looks like fixed at `0.1.54`

**Comment by simPod** [comment]
I can confirm it's fixed. Thanks!

**Comment by DipalPrajapati** [comment]
I am also facing this issues. And I really do not want to  convert string to Date using dateformat?
