### ISSUE TITLE
sslMode=strict completely broken on 0.1.52

### ISSUE THREAD

**Issue by Tapac** [yandex/clickhouse-jdbc#336]
After update to the latest (0.1.52) version we got 
`Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <www.domain.com> doesn't match any of the subject alternative names: [www.domain.com]` when using sslMode=strict.

The problem is in that PR #295 and if to be more precious in the wrong import:
```java
import static javax.net.ssl.HttpsURLConnection.getDefaultHostnameVerifier;
```
`HttpsURLConnection.getDefaultHostnameVerifier()` returns false on any verification request (see implementation below):
```java
private static class DefaultHostnameVerifier implements HostnameVerifier {
        private DefaultHostnameVerifier() {
        }

        public boolean verify(String domain, SSLSession session) {
            return false;
        }
    }
```

I guess what proper import is 
```java
import static org.apache.http.conn.ssl.SSLConnectionSocketFactory.getDefaultHostnameVerifier();
```

**Comment by TanVD** [comment]
:+1:
Having the same issue.
