### ISSUE TITLE
BalancedClickhouseDataSource override custom properties with default if not defined in URI

### ISSUE THREAD

**Issue by seregaSLM** [yandex/clickhouse-jdbc#337]
I am trying to set custom ClickHouseProperties, for example:
```
clickHouseProperties.setSocketTimeout(socketTimeout);
clickHouseProperties.setDataTransferTimeout(dataTransferTimeout);
clickHouseProperties.setMaxExecutionTime(maxExecutionTime);
```
But when I create BalancedClickhouseDataSource in the ClickHouseProperties#merge(second) I get default values for all properties because parameter 'second' after initialize as default properties and override my custom if no one parameter was added to URI. So I add  my parameters to URI add get correct properties configuration. URI parser has a bug in regular expression because this string is not valid:
```
.../db-name?socket_timeout=900000&dataTransferTimeout=900000
```
but this is correct (added compress=1 as first parameter):
```
.../db-name?compress=1&socket_timeout=900000&dataTransferTimeout=900000
```

The second question is why some parameters named in URI for example dataTransferTimeout and others for example socket_timeout?

**Comment by zhyhang** [comment]
same issue +1

**Comment by serebrserg** [comment]
Thanks. Fix for regular expression and merge is merged.
Regarding names - I can't comment on the lack of consistency in naming. The naming may be reviewed in the future to be more consistent, but it isn't easy to change them now. We either need to support both options or to break compatibility.
