### ISSUE TITLE
Clickhouse and Pentaho - Delete and Update

### ISSUE THREAD

**Issue by picinato** [yandex/clickhouse-jdbc#362]
My problem when using Pentaho with Clickhouse are commands that are different from the default.

Examples:

Step update -> Since most databases use the standard sql and the normal update is: update <table> set column = 'value' where <filter>
However in the clickhouse the command is alter table <table_name> update col = expr1 where <filter>

The same happens with delete from table;

Is it possible for JDBC to create an interpreter? When the default command is converted to the clickhouse command?

Thank's for your time.
Quilmer

**Comment by picinato** [comment]
i solved this problem

**Comment by uiliansilvajs** [comment]
how did you solve it? I have the same problem
