### ISSUE TITLE
BC break in patch version: TypeUtils removed

### ISSUE THREAD

**Issue by simPod** [yandex/clickhouse-jdbc#376]
This https://github.com/yandex/clickhouse-jdbc/commit/3be7a3c90a9a8a4bfef8aa0de8822b4bbf43f5b7 removed `TypeUtils` class.

Wanted to ask what is the versioning policy of this library. I relied on ^0.1, should I not consider z in x.y.z as patch version? 

I used to use `TypeUtils.toSqlType(String.class.getCanonicalName())` before 0.1.55, what to use now?

Thanks.

**Comment by alex-krash** [comment]
Sorry, it was my mistake about not mentioning this change.
Could you, please, clarify use case for using this API? We are going to reduce number of public classes from our package, leaving only essentials for JDBC.

**Comment by simPod** [comment]
Yup. I was wondering that this should have been released as 0.2 or something as patch releases should not break backwards 🤔 

I'm doing something like this. I don't fancy it but have not found easier way.

```java
statement.setArray(1, new ClickHouseArray(TypeUtils.toSqlType(String.class.getCanonicalName(), myArray));
```

**Comment by enqueue** [comment]
Sorry, I should have been more careful when removing the utility class, and highlighted this change in the PR.

I would suggest to create Array using [Connection.createArrayOf](https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#createArrayOf-java.lang.String-java.lang.Object:A-)

```
String[] myArray = {"foo", "bar" };
PreparedStatement stmt = connection.prepareStatement(
    "INSERT INTO myTable(foo) VALUES (?)");
stmt.setArray(1, connection.createArrayOf("String", myArray));
```

**Comment by simPod** [comment]
Works great, thanks!

**Comment by alex-krash** [comment]
Thanks for mentioning issue, we'll reduce amount of public API, exposed by library, and we'll announce backward incompatible changes.
