### ISSUE TITLE
Can we have the Jackson dependency removed?

### ISSUE THREAD

**Issue by jcdang** [yandex/clickhouse-jdbc#380]
Also, It looks like `ClickHouseResponse` Isn't even used anymore.  It's only referenced in 1 test.

**Comment by BernieJiangDL** [comment]
can't agree more

**Comment by alex-krash** [comment]
That is not truth.
![Screenshot from 2019-09-02 10-13-22](https://user-images.githubusercontent.com/5325438/64096520-8ef29200-cd6a-11e9-944d-aaa30b1233b2.png)

**Comment by jcdang** [comment]
@alex-krash Yes it is.  Those are transitively unused if you remove the test.

**Comment by alex-krash** [comment]
Since it is part of public contract for ClickhouseStatement interface, we can not drop it, unless declared deprecated, and stopped being used by clients.

**Comment by BernieJiangDL** [comment]
> Since it is part of public contract for ClickhouseStatement interface, we can not drop it, unless declared deprecated, and stopped being used by clients.

then can we have the Jackson dependency update to the lastest version?

**Comment by jcdang** [comment]
@BernieJiangDL If you're using maven you can specify exclusions in dependencies.

**Comment by BernieJiangDL** [comment]
> @BernieJiangDL If you're using maven you can specify exclusions in dependencies.

But the lastest version is incompatible with 2.7.3 version

**Comment by jcdang** [comment]
> > @BernieJiangDL If you're using maven you can specify exclusions in dependencies.
> 
> But the lastest version is incompatible with 2.7.3 version

Adding the exclusion to the pom dependency will remove 2.7.3.

**Comment by doom369** [comment]
@jcdang @BernieJiangDL we just released yesterday an alternative with all unnecessary dependencies removed (jar size now 860kb only). Please check it here - https://github.com/blynkkk/clickhouse4j. Also, we applied a bunch of micro optimizations.
