### ISSUE TITLE
Not able insert using ClickHouseFormat.Values using Writer Interface

### ISSUE THREAD

**Issue by chaitas** [yandex/clickhouse-jdbc#391]
Please let me know how to insert using Values format using send streaming API..

String test = "('10.1','linux','interface','lo0',1,2,3,4,5,6,7,8,9,10,11,nan,nan,nan,nan,'as','lk','poiu','qwert','','','','','','qwertyyu',12345678)";
        
        InputStream result = new ByteArrayInputStream(test.getBytes(StandardCharsets.UTF_8));

        sth.write().sql("Insert into default.tbl_instance_metric_cache (host,source_type,instance,instance_name,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16,c17,c18,c19,c20,c21,c22,c23,c24,c25,timestamp) VALUES").data(result, ClickHouseFormat.Values).send();

It produces following error::
Caused by: java.lang.Throwable: Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected ( before: FORMAT Values\n(\'10.1\',\'linux\',\'interface\',\'lo0\',1,2,3,4,5,6,7,8,9,10,11,nan,nan,nan,nan,\'as\',\'lk\',\'poiu\',\'qwert\',\'\',\'\',\'\',\'\',\'\',\'qwertyyu\',12345678): (at row 1)

Help me with this..

**Comment by alex-krash** [comment]
@chaitas , sorry, documentation is wrong, will fix. Here is a correct example:
```java
        ClickHouseDataSource ds = new ClickHouseDataSource("jdbc:clickhouse://localhost:8123/default");

        ClickHouseConnection connection = ds.getConnection();
        connection.createStatement().execute("CREATE TABLE IF NOT EXISTS default.t1 (id UInt64, v1 Float32, v2 String) ENGINE = Log");

        connection.createStatement()
                .write()
                .sql("INSERT INTO default.t1 (id, v1, v2)")
                .data(new ByteArrayInputStream("(100500, 200.456, 'Hello')".getBytes()), ClickHouseFormat.Values)
                .send();
```
