### ISSUE TITLE
Several databases(shards)

### ISSUE THREAD

**Issue by rasmus93** [yandex/clickhouse-jdbc#4]
Hi!
Could you, please, tell how you work with shards(distributed engine) using your jdbc-driver?
How you do service discovery? You create several datasources and use it or somehow otherwise?
Thanks!

**Comment by serebrserg** [comment]
Hi! 
If you use distributed engine for tables you can query any host from ClickHouse cluster configuration. See https://clickhouse.yandex/reference_en.html#Distributed . 

To achieve redundancy you can create several datasources for several different hosts.

If your application knows which shard to query or you aren't using distributed engine and manage sharding yourself, you can create separate datasources per host. You can group these datasources by shards into some proxies then, having datasources for one or more replicas in one proxy. The proxy may implement some kind of failover. This grouping may be provided by some external configuration or external service discovery implementation.
Implementation of this logic may depend on specific configuration a lot, so it isn't included in the driver.

**Comment by rasmus93** [comment]
Thanks for answer.
I thought maybe you have some special mechanism when one of replica of one shard is unavailable and we need to do somehow "insert" to another replica of this shard.
I understand this mechanism that you described above, thanks
