### ISSUE TITLE
Nested

### ISSUE THREAD

**Issue by sichkarev** [yandex/clickhouse-jdbc#46]
Нет возможности вставлять данные в поля типа Nested через statement. При вставке говорит "No such column".

**Comment by serebrserg** [comment]
Спасибо за отзыв.
Чтобы рассматривать именно эту проблему, добавьте пожалуйста более подробное описание, например, минимальный сценарий:
- create table statement
- insert statement
- minimal code sample
- error description

Если есть возможность, желательно оформить это в виде теста.

**Comment by sichkarev** [comment]
вставилось, прошу прощения
