### ISSUE TITLE
Error trying to parse UInt32 values bigger than Integer.MaxValue

### ISSUE THREAD

**Issue by mitiau** [yandex/clickhouse-jdbc#49]
TypeUtils.toSqlType(String) returns Types.INTEGER for "UInt32" which leads to ClickHouseResultSet.getObject() trying to parse it through getInt(columnIndex) and results in failure for values bigger than Integer.MaxValue.

**Comment by serebrserg** [comment]
Thanks for report.
This is going to be as it is done in mysql driver for example, unsigned types are taken one step up. So that
UInt32 -> Long
UInt64 -> BigInteger

**Comment by serebrserg** [comment]
Merged to master. Will be in the next release version.
