### ISSUE TITLE
jdk version

### ISSUE THREAD

**Issue by Ngalstyan4** [yandex/clickhouse-jdbc#5]
Is EXACTLY jdk 1.6  needed?
Why is this not compiling on a higher version?

**Comment by serebrserg** [comment]
I'll fix the readme. It must compile on any version starting with 1.6. If it isn't please attach the errors.

**Comment by Ngalstyan4** [comment]
_mvn package assembly:single_ command does not seem working
![clickhouse-jdbc](https://cloud.githubusercontent.com/assets/4647374/17057862/1a86e630-502e-11e6-809c-8a63bad51344.png)

It, indeed, seems that assembly plugin is not even added in pom.xml file 

Also, 
`jdbc:clickhouse:localhost:8123`
This is given as an example connection string but it seems
`jdbc:clickhouse://localhost:8123` this is the semantics you are using in tests also regExp checks against this.

Could you also add some documentation about the usage because  it is not really clear even how to execute the simplest queries on the database.

I would be really happy to write a documentation and make a pull request provided you give me some working implementation of this lib with Clickhouse or explain the basic structure of class hierarchy.

**Comment by serebrserg** [comment]
Thanks for pointing out. The readme was quite obsolete. I've updated it with correct urls and updated build configuration.

To see basic examples of querying data you now can check this https://github.com/yandex/clickhouse-jdbc/blob/master/src/test/java/ru/yandex/clickhouse/integration/OnTime.java

It would be great if you write some documentation. 
The basic structure is this:
ClickHouseDriver is a driver class that actually can make connections.
ClickHouseDataSource also can make connections. 
All of this is just an implementation of JDBC interfaces.

ClickHouseConneection is basically a apache http client with some properties. When you execute a query you actually send an http request through this client.
To configure the connections one can use ClickHouseProperties object that contains values for two predefined Enums with properties: ClickHouseConnectionSettings, ClickHouseQueryParam.
The first are for connections in whole. The properties defined in the second are actually passed to every query as url parameters of a request. All this logic can be seen in ClickHouseStatementImpl.

I hope this helps.

**Comment by serebrserg** [comment]
@Ngalstyan4 If you have any questions left you can comment or reopen this issue.
