### ISSUE TITLE
AutoCommit

### ISSUE THREAD

**Issue by rasmus93** [yandex/clickhouse-jdbc#54]
Hi!
As I see in code you have
```java
public void setAutoCommit(boolean autoCommit) throws SQLException {
}
```

It means that ClickHouse supports autocommit by default or there is now commit in ClickHouse?
Or maybe I don't understand something? :)
Thanks!

**Comment by serebrserg** [comment]
Hi.
It means that it is not completely clear what it should do. ClickHouse doesn't have transactions. It only guarantees atomicity in terms of inserting blocks - one block (which has maximum size) can be either inserted completely or isn't inserted at all.
setAutoCommit method can do nothing to change this behavior, but it has to be defined according to JDBC interface. It can do nothing as it does now or throw an exception. I don't think that throwing an exception is better.

**Comment by rasmus93** [comment]
I understood. Yes, it is logical, thanks for clarification!
