### ISSUE TITLE
Cannot override setting (max_execution_time) in readonly mode

### ISSUE THREAD

**Issue by SaltTan** [yandex/clickhouse-jdbc#55]
I cannot connect through the JDBC driver as a readonly user, because " socketTimeout + dataTransferTimeout is sent to ClickHouse as max_execution_time. ", and readonly users cannot run SET statements.
Any query throws an exception
`DB::Exception: Cannot override setting (max_execution_time) in readonly mode`

**Comment by serebrserg** [comment]
Hi,
If "profile" property is not blank, the max_execution_time setting isn't set, so setting "profile" must help.
If you can propose something better, please reopen the issue.

**Comment by SaltTan** [comment]
No, it does not help.
`DB::Exception: Cannot override setting (profile) in readonly mode`

**Comment by serebrserg** [comment]
Do you use the last version of the driver?
There was this logic of calculation max_execution_time, but it was removed in 0.1.7.

**Comment by SaltTan** [comment]
No, I did not.
I checked 0.1.12, a readonly user is able to run queries.
Sorry for the confusion.
