### ISSUE TITLE
getTimestamp and getTime don't use info about CH server's time zone.

### ISSUE THREAD

**Issue by blan4** [yandex/clickhouse-jdbc#76]
Hello.

While working with dates I faced with a TimeZones problem.
More specifically, clickhouse doesn't use timezone in dateTime representation, ok. But when jdbc driver converts a dateTime string with the `SimpleDateFormat` [here](https://github.com/yandex/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java#L25 ) it uses timezone of the host, where jdbc is running but not the clickhouse server!
So, it was not clear to figure out the bug in our system when In our db data stored in UTC, but clients work in, let's say CST. And this is the place where UTC data was shifted to CST that led to a terrible mess.

I think, It would be better to set timezone in jdbc as a property and do this at `ClickHouseResultSet` initialization time: (That actually I do now).
```java
sdf.setTimeZone(TimeZone.getTimeZone("UTC")); // or property value
```

But also I believe that there is a way to get proper timezone of the clickhouse server and use it, instead of local host timezone.

Thanks.

**Comment by serebrserg** [comment]
Hello, thanks for report.
I think the solution must be like this: 
- if use_server_timezone=true, then on connection init query `select timezone()`, if fails - throw exception.
- if use_timezone is not empty, use timezone provided in this property
- if both - throw exception on connection init.

**Comment by ztlpn** [comment]
Note: native client uses exactly this logic, based on the use_client_time_zone setting (it is false by default).

**Comment by serebrserg** [comment]
Merged to master. Will be in next release using server timezone by default.
Please note that this will work only with recent versions of ClickHouse since the function timezone() was added in the end of January. For earlier versions the properties must be overridden to use explicit timezone.
This also will be described in release notes.
