### ISSUE TITLE
Can we move database names from schemas to catalogs?

### ISSUE THREAD

**Issue by tobia** [yandex/clickhouse-jdbc#94]
I have been working on the driver trying to get a few SQL management tools to work (DBeaver and DBVisualizer) but I'm having a hard time with the "current database" popup menus.

Apparently they work well with catalogs, but are very buggy with schemas. Probably because getSchema / setSchema was introduced relatively late into the JDBC standard. (I know, it was years ago with Java 7, but many tools are still behind.)

Since Clickhouse only has one level of namespace (the database name) can we change this driver to expose them as catalogs, instead of schemas? Would you accept a pull request with this change?

**Comment by serebrserg** [comment]
That sounds reasonable, especially having in mind that the driver states java 6 support.
If you find out a consistent combination between schemas and catalogs where catalog refers to database in clickhouse, it would be nice.
It would also be nice if you kept some kind of backward compatibility for those who already use setSchema on connection. If it is not feasible, we can announce the change in changelog and it must be ok.

**Comment by serebrserg** [comment]
Catalogs must be supported now.
