### ISSUE TITLE
Can I download/upload CSV like a PostgreSQL CopyManager

### ISSUE THREAD

**Issue by arturgspb** [yandex/clickhouse-jdbc#99]
First of all, I'm interested in downloading the result of the query into a stream.

https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html

Examples
http://stackoverflow.com/questions/6958965/how-to-copy-a-data-from-file-to-postgresql-using-jdbc

**Comment by serebrserg** [comment]
Currently you can't. There is no CopyManager now, but you can implement one either using jdbc interface (executeQuery/batch insert) or if you would like to contribute CopyManager to this repository, you could use "shortcuts" like getInputStream/sendStream of ClickHouseStatementImpl where the data is basically TSV if you use ClickHouseFormat.TabSeparated (it is used by default).
